name: Build Vue Project

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  

      - name: Install dependencies
        run: npm install

      - name: Install js-cookie
        run: npm install js-cookie
        
      - name: Install morax
        run: npm install pinyin-match
        
      - name: Build project
        run: npm run build

      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
